### ISSUE TITLE
boolean only allows null and true values

### ISSUE THREAD

**Issue by patcon** [frictionlessdata/goodtables-py#134]
I'm getting a warning failure whenever I use a false-value:
https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/helpers.py#L21

I'm getting around this by using null values as false, but that seems odd given the spec:
http://specs.frictionlessdata.io/json-table-schema/#boolean

Any thoughts?

**Comment by pwalsh** [comment]
Hi @patcon 

We'll look at this asap and provide a patch.

**Comment by pwalsh** [comment]
@patcon 

Are you using goodtables from pip? Presumably yes. We are about to release a large, breaking upgrade to goodtables, currently on the [`next` branch](https://github.com/frictionlessdata/goodtables-py/tree/next). If the problem is mitigated in the `next` codebase, would it be a reasonable solution if we do a PR on https://github.com/CivicTechTO/dataset-civictechto-breakout-groups/blob/master/scripts/test_data.py using that instead of the pip installable version? It will help us test `next` so we can get it on master and published to pypi.

**Comment by patcon** [comment]
Cool! Happy to help with testing.

So, I switched over and it's working at least as well as before, but if I add a "N" to a boolean column, I still get the same error I was getting before:
https://gist.github.com/patcon/460fe900a4ba23083b384c9bf20e40ba

So it's doesn't seem like the "next" branch resolves this, unfortunately :(

**Comment by pwalsh** [comment]
@roll can you address this asap please.

**Comment by roll** [comment]
@pwalsh 
ok

**Comment by roll** [comment]
Discovering it - problem should be in jts boolean type I suppose.

**Comment by roll** [comment]
@patcon 
Goodtables.next processes boolean correctly - https://raw.githubusercontent.com/CivicTechTO/dataset-civictechto-breakout-groups/cf6f0ffe0d4e9d98fd186887ddbdef484e6d85bb/data/civictechto-breakout-groups.csv

```bash
$ virtualenv .python
$ source .python/bin/activate
$ pip install git+https://github.com/frictionlessdata/goodtables-py@next
$ python -m goodtables.cli table http://raw.githubusercontent.com/CivicTechTO/dataset-civictechto-breakout-groups/cf6f0ffe0d4e9d98fd186887ddbdef484e6d85bb/data/civictechto-breakout-groups.csv
DATASET
=======
{'error-count': 0, 'table-count': 1, 'time': 1.717, 'valid': True}

TABLE [1]
=========
{'error-count': 0,
 'headers': ['order', 'project', 'person', 'extra', 'date', 'is_onboarding'],
 'row-count': 126,
 'time': 1.714,
 'valid': True}
```
