### ISSUE TITLE
Command line warnings/errors could be more descriptive

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables-py#171]
```
[4,29] [missing-value] Row 4 has a missing value in column 29
```

Would be nicer if it could read:

```
[4,29] [missing-value] Row 4 has a missing value in column '{{ column name }}'
```

**Comment by roll** [comment]
@danfowler 
I'd like to close it as WONTFIX for now because:
- this message we get from Data Quality Spec - https://github.com/frictionlessdata/data-quality-spec - on `goodtables-py` we can't change this message
- also we're going to implement support for tables without headers - https://github.com/frictionlessdata/goodtables-py/issues/176 - and it will make hard to have generalized approach with message template for both kind of tables - with/without headers

Please re-open if needed :+1:

**Comment by danfowler** [comment]
OK!
