### ISSUE TITLE
Feature request: Concept of warnings vs errors

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/goodtables-py#322]
# Overview

Is it possible to specify different levels of importance for different checks? The initial idea is just having warnings and errors but I can imagine also other levels of granularity. This would be tied in to an update to the goodtables-ui to show these checks with different colors.  

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by pwalsh** [comment]
This was the original intention with the `weight` property in the [data quality spec](https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json) (which good tables uses).

**Comment by cschloer** [comment]
Thanks for the reply! So to clarify: the concept exists within the spec but it hasn't been implemented in the goodtables library?

**Comment by roll** [comment]
@cschloer 
Weight of errors is a part of the spec - https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json. It's not used in `goodtables-ui` yet.

After we have merged  - https://github.com/frictionlessdata/goodtables-ui/pull/29 - and you're able to customize the spec it can be used for the purpose you've described in this issue.

I've added this request to - https://github.com/frictionlessdata/goodtables-ui/issues/28

I'm closing this issue (will handle in goodtables-ui/28) because on `goodtables-py` level it's already possible to use these weights:

```python
# pseudo-code
import goodtables

report = goodtables.validate()
for error in report['tables'][0]['errors']:
  weight = goodtables.spec['errors'][error['code']]['weight']
  # handle weight on the client level
```

**Comment by roll** [comment]
Let's think in https://github.com/frictionlessdata/goodtables-ui/issues/28 what kind of visual customizations make sense to add:
- color-intensity/etc based on weights
- color-intensity/etc based on some tag like `low/high/etc` severity mapped to error-codes
- etc
